### ISSUE TITLE
Buy space should have same fields as rent during purchase

### ISSUE THREAD

**Issue by easonchai** [decentramall/decentramall-ui#56]
Related to #52

**Comment by obernardovieira** [comment]
what do you mean exactly?

**Comment by easonchai** [comment]
Right now if we buy a space, we cant use it. We have to rent a space to have a title, description, etc.

**Comment by obernardovieira** [comment]
That's right. You buy the SPACE. You own it now. Someone else will rent it to you, to use it to advertise their space.
